### ISSUE TITLE
Uncaught TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/cu-patcher-ui#139]
Stack Trace:

Sidebar._this.playSelect @ cu-patcher-ui.js:66217
Sidebar._this.onSelectedChannelChanged @ cu-patcher-ui.js:66239
ChannelSelect._this3.onSelectedChannelChanged @ cu-patcher-ui.js:65134
QuickSelect._this.onItemSelect @ cu-patcher-ui.js:21469
...

**Comment by sysrage** [comment]
As of PR #143 this is resolved.

**Comment by Mehuge** [comment]
!fixed
